"""
AI Summary API Routes
=====================

Provides an endpoint that takes a full portfolio risk report JSON payload and
returns a concise, professional risk summary generated by GPT-4o.

Endpoint:
  POST /api/ai/summary
"""

from __future__ import annotations

import logging
import os
from typing import Any, Dict, List

from dotenv import load_dotenv
from flask import Blueprint, jsonify, request
from openai import OpenAI, OpenAIError

logger = logging.getLogger(__name__)

# Load environment variables from .env (if present)
load_dotenv()

ai_bp = Blueprint("ai_summary", __name__)


def _get_openai_client() -> OpenAI | None:
    """
    Initialise and return an OpenAI client if the API key is configured.

    Returns
    -------
    OpenAI | None
        Client instance when `OPENAI_API_KEY` is set, otherwise ``None``.
    """
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return None
    return OpenAI(api_key=api_key)


def _validate_payload(data: Dict[str, Any]) -> tuple[bool, str]:
    """
    Validate that the incoming JSON payload contains the minimum required keys.

    Parameters
    ----------
    data : dict
        Parsed JSON body from the request.

    Returns
    -------
    (bool, str)
        Tuple of (is_valid, error_message). When valid, error_message is empty.
    """
    if not isinstance(data, dict):
        return False, "Request body must be a JSON object."

    missing: List[str] = []
    for key in ("positions", "greeks", "fragility"):
        if key not in data:
            missing.append(key)

    if missing:
        return (
            False,
            f"Missing required fields: {', '.join(missing)}. "
            "Expected: positions, greeks, fragility.",
        )

    return True, ""


def _format_positions(positions: List[Dict[str, Any]]) -> str:
    """Format portfolio legs into a readable bullet list for the prompt."""
    lines: List[str] = []
    for p in positions[:200]:  # hard safety cap
        underlying = str(p.get("underlying", "N/A")).upper()
        opt_type = str(p.get("type", "")).upper()
        strike = p.get("strike", "—")
        expiry = p.get("expiry", "—")
        qty = p.get("qty", 0)
        iv = p.get("iv")
        mtm = p.get("mtm_pnl")

        parts = [
            f"{underlying} {opt_type} {strike} @ {expiry}",
            f"qty {qty:+d}",
        ]
        if iv is not None:
            parts.append(f"IV ~ {round(float(iv) * 100, 1)}%")
        if mtm is not None:
            parts.append(f"MTM ₹{round(float(mtm)):,}")

        lines.append("- " + " | ".join(parts))

    if not lines:
        return "No positions found."

    return "\n".join(lines)


def _format_fragility(fragility: Dict[str, Any]) -> tuple[str, str]:
    """
    Format fragility score, state, and component breakdown for the prompt.

    Returns
    -------
    (score_line, breakdown)
    """
    score = fragility.get("score", 0)
    state = fragility.get("state", "UNKNOWN")
    components = fragility.get("components", {})

    score_line = f"{score}/100 — {state}"

    if not components:
        return score_line, "No fragility breakdown available."

    lines: List[str] = []
    for name, comp in components.items():
        label = str(name).capitalize()
        comp_score = comp.get("score", 0)
        desc = comp.get("label") or comp.get("explanation") or ""
        line = f"- {label}: {comp_score}/100"
        if desc:
            line += f" — {desc}"
        lines.append(line)

    return score_line, "\n".join(lines)


def _format_exposure(report: Dict[str, Any]) -> Dict[str, Any]:
    """Extract and normalise basic exposure and P&L metrics."""
    exposure = report.get("exposure", {}) or {}
    fragility = report.get("fragility", {}) or {}

    gross = exposure.get("gross_inr")
    net = exposure.get("net_inr")
    margin_used = fragility.get("margin_used")
    mtm = report.get("total_mtm_pnl")

    return {
        "gross": gross if gross is not None else 0.0,
        "net": net if net is not None else 0.0,
        "margin_used": margin_used if margin_used is not None else 0.0,
        "mtm": mtm if mtm is not None else 0.0,
    }


def _format_vol_intel(iv_intel: Dict[str, Any]) -> str:
    """Format IV intelligence section for the prompt."""
    if not iv_intel:
        return "No IV intelligence available."

    lines: List[str] = []
    for underlying, rep in iv_intel.items():
        cur_iv = rep.get("current_iv")
        rank = rep.get("iv_rank")
        pct = rep.get("iv_percentile")
        hv = rep.get("hv_20d")
        spread = rep.get("iv_hv_spread")

        parts = [f"{underlying}: IV {cur_iv}% (Rank {rank}, Pct {pct}%)"]
        if hv is not None and spread is not None:
            sign = "+" if spread >= 0 else ""
            parts.append(f"HV {hv}% | IV-HV {sign}{spread} pts")

        lines.append("- " + " | ".join(str(x) for x in parts))

    return "\n".join(lines)


def _format_stress_scenarios(report: Dict[str, Any]) -> str:
    """
    Extract and format worst 5 stress scenarios if they are present in the
    report payload. The frontend may choose to enrich the report before
    calling this endpoint.
    """
    scenarios = report.get("stress_scenarios") or report.get("scenarios") or []
    if not scenarios:
        return "Stress scenario detail not provided."

    # Sort by P&L ascending (worst first)
    try:
        scenarios_sorted = sorted(
            scenarios,
            key=lambda s: float(s.get("total_pnl", 0.0)),
        )
    except Exception:  # pragma: no cover - purely defensive
        scenarios_sorted = scenarios

    lines: List[str] = []
    for s in scenarios_sorted[:5]:
        name = s.get("scenario", "Unnamed")
        pnl = s.get("total_pnl", 0.0)
        lines.append(f"- {name}: P&L ₹{round(float(pnl)):,}")

    return "\n".join(lines) if lines else "Stress scenario detail not provided."


def _build_prompt(report: Dict[str, Any]) -> str:
    """
    Construct the full prompt text using the provided portfolio report.

    This follows the template described in the product specification and
    injects the relevant metrics from the JSON body.
    """
    positions = report.get("positions", [])
    greeks = report.get("greeks", {})
    fragility = report.get("fragility", {})
    iv_intel = report.get("iv_intelligence", {})

    formatted_legs = _format_positions(positions)
    score_line, frag_breakdown = _format_fragility(fragility)
    exposure = _format_exposure(report)
    vol_section = _format_vol_intel(iv_intel)
    stress_section = _format_stress_scenarios(report)

    net_delta = greeks.get("net_delta", 0.0)
    net_gamma = greeks.get("net_gamma", 0.0)
    net_theta = greeks.get("net_theta", 0.0)
    net_vega = greeks.get("net_vega", 0.0)

    prompt = f"""
        You are a senior derivatives risk manager reviewing an Indian F&O options portfolio.

        Provide a concise professional risk summary in 4 sections:

        1. Portfolio Overview (in simple terms, not just writing the positions)
        2. Key Risk Flags (2–3 most important)
        3. Stress Sensitivity (in simple terms, not just writing the scenarios)
        4. Trader's Edge Assessment (in simple terms, not just writing the technical assessment)

        Tone: direct, but expalining the risk in a way that is easy to understand and not too technical.
        Max 500 words.

        --- PORTFOLIO DATA ---

        Positions:
        {formatted_legs}

        Portfolio Greeks:
        Net Delta: {net_delta}
        Net Gamma: {net_gamma}
        Net Theta: {net_theta}
        Net Vega: {net_vega}

        Fragility Score: {score_line}
        Fragility Breakdown:
        {frag_breakdown}

        Exposure:
        Gross Notional: ₹{exposure['gross']:,}
        Net Exposure: ₹{exposure['net']:,}
        Margin Used: ₹{exposure['margin_used']:,}
        MTM: ₹{exposure['mtm']:,}

        Volatility Intelligence:
        {vol_section}

        Worst 5 Stress Scenarios:
        {stress_section}
""".strip()

    return prompt


@ai_bp.route("/summary", methods=["POST"])
def generate_ai_summary():
    """
    Generate an AI-driven risk summary for a portfolio.

    Expects a full risk report JSON body (the same structure returned by the
    portfolio analysis endpoint). The handler validates that `positions`,
    `greeks`, and `fragility` are present, then calls GPT-4o via the OpenAI
    Chat Completions API and returns a Markdown-formatted summary.

    Response
    --------
    200
        ``{"summary": "<markdown>"}``
    400
        Validation errors (missing required fields or invalid JSON).
    500
        Upstream OpenAI error or missing API key.
    """
    data = request.get_json(force=True, silent=True) or {}

    is_valid, error_msg = _validate_payload(data)
    if not is_valid:
        return jsonify({"error": error_msg}), 400

    client = _get_openai_client()
    if client is None:
        return jsonify({"error": "API key not configured"}), 500

    prompt = _build_prompt(data)

    try:
        completion = client.responses.create(
            model="gpt-5-nano",
            input=prompt,
            store=False,
        )
        content = (
            completion.output_text
            if completion.error is None
            else ""
        )
        if not content:
            raise RuntimeError("Empty response from OpenAI.")

        return jsonify({"summary": content}), 200

    except OpenAIError as exc:
        logger.exception("OpenAI API error while generating AI summary: %s", exc)
        return (
            jsonify({"error": "Failed to generate AI summary from OpenAI."}),
            500,
        )
    except Exception as exc:  # pragma: no cover - purely defensive
        logger.exception("Unexpected error while generating AI summary: %s", exc)
        return (
            jsonify({"error": "Unexpected error while generating AI summary."}),
            500,
        )

